inherit_from:
  - .rubocop_todo.yml
  - https://relaxed.ruby.style/rubocop.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 4.0
  Exclude:
  - 'lib/dry-cli-ui.rb'
  - 'vendor/**/*'
  - 'bin/**/*'
  - 'tmp/**/*'
  - 'spec/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false
